#! /usr/bin/env python
#
# ROS Node and HMI Client of yapykaldi ASR app

import rospy
from yapykaldi_ros import HMIServerYapykaldi

if __name__ == "__main__":
    rospy.init_node('yapykaldi_hmi_node')
    rospy.loginfo("Creating HMIServerYapykaldi")
    c = HMIServerYapykaldi()

    rospy.logdebug("Registering HMIServerYapykaldi shutdown hook")

    def shutdown():
        rospy.loginfo("Shutting down HMIServerYapykaldi")
        c.stop()

    rospy.on_shutdown(shutdown)
    rospy.logdebug("Registered HMIServerYapykaldi shutdown hook")
    rospy.spin()
